server:
  port: 8888

spring:
  threads:
    virtual:
      enabled: true

jwt:
  secret: dGhpc0lzQVRoZW50aWN0aGlydHlUd29CaXRzU2VjcmV0ICE
  expire: 3600s
  header: access-token

datasource:
  username: postgres
  password: 123456
  url: jdbc:postgresql://localhost:5432/postgres
  driver: org.postgresql.Driver
